language: java

jdk:
  - oraclejdk8

git:
  depth: 5

branches:
 only:
  - master

sudo: required

install: true

script:
  - chmod +x ./gradlew
  - ./gradlew build
  - ./gradlew --stop

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/