language: java

sudo: false

jdk:
  - oraclejdk8

os:
  - linux

git:
  depth: 5

branches:
 only:
  - master

script:
  - chmod +x ./gradlew
  - ./gradlew build
  - ./gradlew --stop

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/